# Generated by Django 4.1.5 on 2023-06-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_alter_profile_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='profile_id',
        ),
    ]
