# Generated by Django 4.1.5 on 2023-06-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Name of the Service')),
                ('region', models.CharField(blank=True, max_length=225, null=True, verbose_name='Region of service')),
                ('description', models.CharField(blank=True, max_length=225, null=True, verbose_name='Description of the Service')),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.TextField(default='None', verbose_name='Address of the Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(default='None', max_length=225, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='motto',
            field=models.CharField(default='None', max_length=225, verbose_name='Name of the Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.IntegerField(default='12345678912', max_length=11, verbose_name='Phone number of the Company'),
        ),
        migrations.AddField(
            model_name='about',
            name='slogan',
            field=models.CharField(default='None', max_length=225, verbose_name='Name of the Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(default='None', verbose_name='About the Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='company_name',
            field=models.CharField(default='None', max_length=225, verbose_name='Name of the Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='history',
            field=models.TextField(default='None', verbose_name='History of the Company'),
            preserve_default=False,
        ),
    ]
