# Generated by Django 4.1.5 on 2023-06-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_service_about_address_about_email_about_motto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
